### ISSUE TITLE
add google-java-format

### ISSUE THREAD

**Issue by ghost** [sum01/fmt-micro#19]
[https://github.com/google/google-java-format](https://github.com/google/google-java-format)

## [usage](https://github.com/google/google-java-format#from-the-command-line)
```
java -jar /path/to/google-java-format-1.5-all-deps.jar <options> [files...]
```
The formatter can act on whole files, on limited lines (--lines), on specific offsets (--offset), passing through to standard-out (default) or altered in-place (--replace).

**Comment by sum01** [comment]
Hmm. So it doesn't have its own executable? I'm wondering how I'm supposed to figure out where that `google-java-format-1.5-all-deps.jar` actually is to be able to run this.

**Comment by ghost** [comment]
You could probably have a config option in the settings file for that path

**Comment by sum01** [comment]
If you require the functionality at the moment, just update `fmt` to 3.2, then add the path into your own custom formatter like so
`"fmt|java": "java -jar /path/to/google-java-format-1.5-all-deps.jar --replace"`

This seems like something that would do well to be bundled, so that I can know where it's located. Probably put the `.jar` in `configs/google-java-format`, but I'll have to keep it updated myself.

**Comment by sum01** [comment]
~Although I think that command might need some work, I didn't check their docs yet on how to do an in-place...~ Updated previous command, should be good

**Comment by ghost** [comment]
can't get it to work, how am I supposed to edit the settings?
currently `"java-formatter": "uncrustify",` works, should I delete that line or....?
I just added your command/ tried your command + `"java-formatter": "",` but it did not work

(and updated your plugin, a shame that micro still has this update bug so I have to manually select the one)

**Comment by sum01** [comment]
Nah, you can simply create that entirely new option. I added it here https://github.com/sum01/fmt-micro/commit/01b38311ab20c37b74081d13f0f6b654f7a1b913

It looks for `fmt|langname` and uses that instead of whatever is declared in `langname-formatter` (if found).

So just copy that entire command, fix the path, then add it as a new line in your `settings.json`. [Docs](https://github.com/sum01/fmt-micro#using-custom-formatterargs)

**Comment by ghost** [comment]
~~yes that is what I did very first but did not work~~
never mind now it works, maybe the java execution of the formatter was just bit sluggish, thanks for the super quick response

**Comment by sum01** [comment]
Then perhaps the command itself doesn't work. I just tested `"fmt|java": "echo 'test'"` and it worked.

**Comment by sum01** [comment]
I downloaded the file and tested on some example code, and it works just fine.

Perhaps you have the wrong path in the settings? There might be a helpful error in Micro's log (CtrlE 'log')

**Comment by ghost** [comment]
I did edit my post, sorry for the confusion, it works properly, thanks for the quick response!

**Comment by sum01** [comment]
So I think I'm going to not add this as a built-in formatter, since that would require bundling it with the repo. Bundling would go against the idea of the user supplying their own binaries/whatever and at the version they want.

Plus the custom formatter option works for people that still want it 😄 

Once more, I'll post the option for anyone interested
> "fmt|java": "java -jar /path/to/google-java-format-1.5-all-deps.jar --replace"
